name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch: # 개발자가 수동으로 클릭해서 수행하는 이벤트

jobs:
  build:
    env:
      JOB_ENV: job!
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: Print Repository Variable
        env:
          STEP_ENV: step!
        run: |
          echo $JOB_ENV
          echo $STEP_ENV
          echo ${{ vars.MESSAGE }}

      - name: Print Repository Secrets
        run: |
          echo ${{ secrets.SECRET_VARIABLE }}